### ISSUE TITLE
Semantic search failed: Semantic search failed: No embeddings available for search

### ISSUE THREAD

**Issue by torarnv** [bartolli/codanna#41]
```
❯ codanna index src/gui --progress
Loading embedding model from cache...
Semantic search enabled (model: AllMiniLML6V2, threshold: 0.6)
Indexing directory: src/gui
Indexing: 835/835 files (100%) - 31 files/s - ETA: 0s
DEBUG: resolve_cross_file_relationships: 564287 unresolved relationships

Indexing Complete:
  Files indexed: 835
  Files failed: 0
  Symbols found: 309
  Time elapsed: 0.00s
  Performance: inf files/second
  Average symbols/file: 0.4

Saving index with 385618 total symbols, 24 total relationships...
Index saved to: /Users/torarne/dev/qt/qtbase/.codanna/index

❯ codanna mcp semantic_search_docs query:"who calls QWindow::setGeometry" limit:3
Semantic search failed: Semantic search failed: No embeddings available for search

```

**Comment by torarnv** [comment]
Doesn't seem to find the correct symbols either:

```
❯ codanna mcp search_symbols query:"who calls QWindow::setGeometry" limit:3
No results found for query: who calls QWindow::setGeometry

❯ codanna mcp search_symbols query:"which functions does QWindow have" limit:3
Found 3 result(s) for query 'which functions does QWindow have':

1. functions (Function)
   File: ./src/3rdparty/pcre2/src/pcre2_jit_misc.c:84
   Module: src::3rdparty::pcre2::src::pcre2_jit_misc::functions
   Score: 212.98

2. functions (Function)
   File: ./src/3rdparty/pcre2/src/pcre2_jit_match.c:108
   Module: src::3rdparty::pcre2::src::pcre2_jit_match::functions
   Score: 212.98

3. functions (Function)
   File: ./src/3rdparty/pcre2/src/pcre2_jit_misc.c:84
   Module: src::3rdparty::pcre2::src::pcre2_jit_misc::functions
   Score: 212.98
```

https://github.com/qt/qtbase/blob/dev/src/gui/kernel/qwindow.h

**Comment by sergitorres-codere** [comment]
I checked a bit because I faced a similar issue and i believe it is linked to the fact that the CPP parser does not include the .h extension, although that does not fix the find_callers part. I will try to submit a PR later or tomorrow for both issues.

**Comment by torarnv** [comment]
@sergitorres-codere I thought so too at first, but I had added `.h` files explicitly to the settings file. 

But I'm not sure I'm quering it correctly. What syntax would be a sure-fire check to see if the index is working for a C++ project?

**Comment by torarnv** [comment]
I tried upgrading to v0.5.23 now, and maybe it's me holding it wrong, but the results do not match what I was expecting:

```
❯ rm -Rf .codanna/index

❯ codanna index src/gui --progress
Loading embedding model from cache...
Semantic search enabled (model: AllMiniLML6V2, threshold: 0.6)
Indexing directory: src/gui
Progress: [▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮] 100%
835/835 files | 835 indexed | 41/s | 20.6s
Resolving cross-file relationships: 617489 unresolved entries
Progress: [▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮] 100%
617489/617489 relationships | 2616 resolved | 585057 skipped | 113891/s | 5.4s

Indexing Complete:
  Files indexed: 835
  Files failed: 0
  Symbols found: 309
  Time elapsed: 0.00s
  Performance: inf files/second
  Average symbols/file: 0.4

Saving index with 68224 total symbols, 5232 total relationships...
Index saved to: /Users/torarne/dev/qt/qtbase/.codanna/index

❯ codanna mcp search_symbols query:"which functions does QWindow have" limit:3
Found 3 result(s) for query 'which functions does QWindow have':

1. functions (Function)
   File: src/gui/kernel/qopenglcontext_p.h:69
   Module: src::gui::kernel::qopenglcontext_p::functions
   Score: 213.18

2. <QtGui/qopenglfunctions.h> (Function)
   File: src/gui/opengl/qopenglextrafunctions.h:10
   Module: src::gui::opengl::qopenglextrafunctions::<QtGui/qopenglfunctions.h>
   Score: 104.61

3. <QtCore/qhashfunctions.h> (Function)
   File: src/gui/text/windows/qwindowsfontdatabase_p.h:22
   Module: src::gui::text::windows::qwindowsfontdatabase_p::<QtCore/qhashfunctions.h>
   Score: 104.61
```

I was expecting it to understand and list the members of the QWindow class:
https://github.com/qt/qtbase/blob/dev/src/gui/kernel/qwindow.h

```
❯ codanna mcp semantic_search_docs query:"Tell me about QWindow::setGeometry"
Found 10 semantically similar result(s) for 'Tell me about QWindow::setGeometry':

1. StrokeHandler (Struct) - Similarity: 0.472
   File: src/gui/painting/qpaintengineex.cpp:120
   Doc: *****************************************************************************  class QPaintEngineExPrivate:

2. qt_path_stroke_move_to (Function) - Similarity: 0.459
   File: src/gui/painting/qpainterpath.cpp:2494
   Doc: ***************************************************************************** class QPainterPathStroker

3. QVectorPath::~QVectorPath (Function) - Similarity: 0.452
   File: src/gui/painting/qpaintengineex.cpp:27
   Doc: *****************************************************************************  class QVectorPath

4. QDashStroker::QDashStroker (Function) - Similarity: 0.407
   File: src/gui/painting/qstroker.cpp:981
   Doc: ***************************************************************************** QDashStroker members

5. QTextDocumentPrivate::aboutToRemoveCell (Function) - Similarity: 0.396
   File: src/gui/text/qtextdocument_p.cpp:1717
   Doc: This method is called from QTextTable when it is about to remove a table-cell to allow cursors to update their selection.

6. adapted_angle_on_x (Function) - Similarity: 0.300
   File: src/gui/painting/qstroker.cpp:143
   Doc: ***************************************************************************** QLineF::angleTo gives us the angle between two lines with respecting the direction. Here we want to identify the line's angle direction on the unit circle.

7. hex2byte (Function) - Similarity: 0.142
   File: src/gui/image/qxbmhandler.cpp:29
   Doc: ***************************************************************************   X bitmap image read/write functions ***************************************************************************

8. fbname (Function) - Similarity: 0.128
   File: src/gui/image/qxpmhandler.cpp:735
   Doc: ***************************************************************************   Misc. utility functions ***************************************************************************

9. interpolate_4_pixels_16 (Function) - Similarity: 0.106
   File: src/gui/painting/qdrawhelper.cpp:1166
   Doc: \internal   interpolate 4 argb pixels with the distx and disty factor.   distx and disty must be between 0 and 16

10. pixelToPoint (Function) - Similarity: 0.089
   File: src/gui/text/qtextodfwriter.cpp:31
   Doc: Convert pixels to postscript point units
```

I was expecting it to give me the docs from https://github.com/qt/qtbase/blob/dev/src/gui/kernel/qwindow.cpp#L1848

```
❯ codanna mcp search_symbols query:"who calls QWindow::setGeometry" limit:3
No results found for query: who calls QWindow::setGeometry
```
I was expecting a list of functions that call QWindow::setGeometry.

**Comment by bartolli** [comment]
Hey @torarnv, I’ve updated the C++ parser and cross-file resolution logic.
Please upgrade to the latest release using:
`cargo install codanna --all-features --force`
Then re-index with:
`codanna index . --force --progress`

Check the version to make sure upgrade was successfull: codanna --version (0.5.23)
Let me know once you’ve had a chance to try the fixed version.

**Comment by bartolli** [comment]
EDIT: I found the bug and I have fixed it. Will push a new release later tonight.

**Comment by bartolli** [comment]
also to analyze impact:
`codanna mcp analyze_impact QWindow lang:cpp`

**Comment by torarnv** [comment]
Thanks! Here's what I see:

```
❯ codanna --version
codanna 0.5.23

❯ codanna index src/gui --force --progress
Force re-indexing requested, creating new index
Loading embedding model from cache...
Semantic search enabled (model: AllMiniLML6V2, threshold: 0.6)
Indexing directory: src/gui
Progress: [▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮] 100%
835/835 files | 835 indexed | 40/s | 20.8s
Resolving cross-file relationships: 617489 unresolved entries
Progress: [▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮] 100%
617489/617489 relationships | 2615 resolved | 589457 skipped | 108372/s | 5.7s

Indexing Complete:
  Files indexed: 835
  Files failed: 0
  Symbols found: 309
  Time elapsed: 0.00s
  Performance: inf files/second
  Average symbols/file: 0.4

Saving index with 68224 total symbols, 5230 total relationships...
Index saved to: /Users/torarne/dev/qt/qtbase/.codanna/index

❯ codanna mcp semantic_search_with_context query:"which functions does QWindow have" limit:3
Found 3 results for query: 'which functions does QWindow have'

1. StrokeHandler - Struct at src/gui/painting/qpaintengineex.cpp:120
   Similarity Score: 0.547
   Documentation:
     *****************************************************************************

     class QPaintEngineExPrivate:

2. qt_path_stroke_move_to - Function at src/gui/painting/qpainterpath.cpp:2494
   Similarity Score: 0.473
   Documentation:
     *****************************************************************************
     class QPainterPathStroker

3. QVectorPath::~QVectorPath - Function at src/gui/painting/qpaintengineex.cpp:27
   Similarity Score: 0.466
   Documentation:
     *****************************************************************************

     class QVectorPath

❯ codanna mcp analyze_impact QWindow lang:cpp
No symbols would be impacted by changing QWindow
```

**Comment by bartolli** [comment]
@torarnv Yes, I found the problem. It was not walking down the children for methods. Now it's fixed but will make a release in about an hour or two. Thanks for catching this.

**Comment by bartolli** [comment]
@torarnv v0.5.25 includes the fixes for all the issues in this thread. Please update to the latest version and confirm if everything works as expected. The analyze_impact has been fixed too and should function correctly now.

**Comment by torarnv** [comment]
Thanks @bartolli ! I'm testing with the latest release now, and the results still don't make sense to me, but I'm not sure if I'm querying it correctly:

```
❯ codanna --version
codanna 0.5.26

❯ rm -Rf .codanna/index

❯ codanna index src/gui --force --progress
Loading embedding model from cache...
Semantic search enabled (model: AllMiniLML6V2, threshold: 0.6)
Indexing directory: src/gui
Progress: [▮▮▮▮▮▮▮▮▮                   ]  31%
Progress: [▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮] 100%
835/835 files | 835 indexed | 42/s | 20.0s
Resolving cross-file relationships: 601546 unresolved entries
Progress: [▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮▮] 100%
601546/601546 relationships | 12739 resolved | 556523 skipped | 209065/s | 2.9s

Indexing Complete:
  Files indexed: 835
  Files failed: 0
  Symbols found: 309
  Time elapsed: 0.00s
  Performance: inf files/second
  Average symbols/file: 0.4

Saving index with 68485 total symbols, 25478 total relationships...
Index saved to: /Users/torarne/dev/qt/qtbase/.codanna/index

❯ codanna mcp semantic_search_with_context query:"which functions does QWindow have" limit:3
Found 3 results for query: 'which functions does QWindow have'

1. StrokeHandler - Struct at src/gui/painting/qpaintengineex.cpp:120
   Similarity Score: 0.547
   Documentation:
     *****************************************************************************

     class QPaintEngineExPrivate:

2. qt_path_stroke_move_to - Function at src/gui/painting/qpainterpath.cpp:2494
   Similarity Score: 0.473
   Documentation:
     *****************************************************************************
     class QPainterPathStroker

   qt_path_stroke_move_to calls 1 function(s):
     -> Method moveTo at src/gui/painting/qpainterpath.cpp:679

3. QVectorPath::~QVectorPath - Method at src/gui/painting/qpaintengineex.cpp:27
   Similarity Score: 0.466
   Documentation:
     *****************************************************************************

     class QVectorPath



❯ codanna mcp analyze_impact QWindow lang:cpp
No symbols would be impacted by changing QWindow (checked 4 symbol(s) with this name)

❯ codanna mcp search_symbols query:"who calls QWindow::setGeometry" limit:3
No results found for query: who calls QWindow::setGeometry

❯ codanna mcp semantic_search_docs query:"Tell me about QWindow::setGeometry"
Found 10 semantically similar result(s) for 'Tell me about QWindow::setGeometry':

1. StrokeHandler (Struct) - Similarity: 0.472
   File: src/gui/painting/qpaintengineex.cpp:120
   Doc: *****************************************************************************  class QPaintEngineExPrivate:

2. qt_path_stroke_move_to (Function) - Similarity: 0.459
   File: src/gui/painting/qpainterpath.cpp:2494
   Doc: ***************************************************************************** class QPainterPathStroker

3. QVectorPath::~QVectorPath (Method) - Similarity: 0.452
   File: src/gui/painting/qpaintengineex.cpp:27
   Doc: *****************************************************************************  class QVectorPath

4. QDashStroker (Method) - Similarity: 0.407
   File: src/gui/painting/qstroker.cpp:981
   Doc: ***************************************************************************** QDashStroker members

5. aboutToRemoveCell (Method) - Similarity: 0.396
   File: src/gui/text/qtextdocument_p.cpp:1717
   Doc: This method is called from QTextTable when it is about to remove a table-cell to allow cursors to update their selection.

6. adapted_angle_on_x (Function) - Similarity: 0.300
   File: src/gui/painting/qstroker.cpp:143
   Doc: ***************************************************************************** QLineF::angleTo gives us the angle between two lines with respecting the direction. Here we want to identify the line's angle direction on the unit circle.

7. hex2byte (Function) - Similarity: 0.142
   File: src/gui/image/qxbmhandler.cpp:29
   Doc: ***************************************************************************   X bitmap image read/write functions ***************************************************************************

8. fbname (Function) - Similarity: 0.128
   File: src/gui/image/qxpmhandler.cpp:735
   Doc: ***************************************************************************   Misc. utility functions ***************************************************************************

9. interpolate_4_pixels_16 (Function) - Similarity: 0.106
   File: src/gui/painting/qdrawhelper.cpp:1166
   Doc: \internal   interpolate 4 argb pixels with the distx and disty factor.   distx and disty must be between 0 and 16

10. pixelToPoint (Function) - Similarity: 0.089
   File: src/gui/text/qtextodfwriter.cpp:31
   Doc: Convert pixels to postscript point units
```

1. Why does `codanna mcp semantic_search_with_context query:"which functions does QWindow have" limit:3` list classes from random files, instead of the member functions of the class `QWindow`?
2. Why does `codanna mcp analyze_impact QWindow lang:cpp` only claim there are 4 symbols?
3. Why does `codanna mcp search_symbols query:"who calls QWindow::setGeometry" limit:3` claim there are no callers of `setGeometry`?  There's clearly calls like `QWindow::setPosition` calling `QWindow::setGeometry`
4. Why does `codanna mcp semantic_search_docs query:"Tell me about QWindow::setGeometry"` list random doc strings from random files, instead of giving the docs of https://doc.qt.io/qt-6/qwindow.html#setGeometry ?
